name: Deploy Docs to GitHub Pages
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocs-static-i18n

      - name: Build docs
        run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DOCS_DEPLOY_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          cname: tech.degica.com/komoju-woocommerce
          full_commit_message: "Deploy docs from CI"
